##redis-cli

## Sign Up
## customer sign up
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "citizenID": "1122233165487",
  "email": "email@gmail.com",
  "password": "12345678",
  "passwordConfirm": "12345678",
  "name": "s1",
  "surname": "ss1",
  "phone": "0918652376",
  "birth": "05/05/1990",
  "genderID": 1,
  "marriedStatusID": 1,
  "religion": "พุทธ",
  "forgotPasswordQuestID": 1,
  "forgotPasswordAns": "test1",
  "address": "",
  "subDistrict": "ขามเรียง",
  "district": "กันทรวิชัย",
  "provinceCode": "81",
  "zipcode": "4415"
}

###

## Sign In
## customer sign up
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
  "username": "a@gmail.com",
  "password": "tnUA0mzJcM"
}

###

## Sign out
POST http://localhost:8000/auth/signout
Content-Type: application/json
X-Token: a-vmT6KyTwwYFKyfOYHW7-hJoKMdlRIV5sg8uPl4ghA

{
  "token": "a-vmT6KyTwwYFKyfOYHW7-hJoKMdlRIV5sg8uPl4ghA"
}

###

GET http://localhost:8000/hello
X-Token: dztji53prvNVnC5oWyB-Lz2eriyHVn1bHtxqSUHiZsQ

###
