##redis-cli

## Sign Up
## customer sign up
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "12345678",
  "passwordConfirm": "12345678",
  "name": "s1",
  "surname": "ss1",
  "phone": "0918652376",
  "birth": "05/05/19",
  "genderID": 1,
  "marriedStatusID": 1,
  "religion": "พุทธ",
  "Address": "",
  "subDistrict": "ขามเรียง",
  "district": "กันทรวิชัย",
  "provinceCode": "81",
  "zipcode": "44150rere"
}

###

## Sign In
## customer sign up
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
  "username": "kk@gmail.com",
  "password": "123456"
}

###

## Sign out
POST http://localhost:8000/auth/signout
Content-Type: application/json
X-Token: h6rY76Rong4Ur2QA-tNlerqfjwG1s730DzLb4ta_YwY

{
}

###

GET http://localhost:8000/hello
X-Token: A3RemUxT_WLp38McAHGO6q9672ihLZu0gSBq8-n1WRY

###