## Sign In
## customer sign up
POST http://localhost:8000/forgot_password/get_question_option
Content-Type: application/json

{}

###

## Sign In
## customer sign up
POST http://localhost:8000/forgot_password/get_question
Content-Type: application/json

{
  "email": "a@gmail.com"
}

###

## customer sign up
POST http://localhost:8000/forgot_password/set_new_password
Content-Type: application/json

{
  "email": "a@gmail.com",
  "answer": "ส้มตำ"
}

###
