## Sign In
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
  "username": "korn@gmail.com",
  "password": "korn0112"
}

###

## Sign In
POST http://localhost:8000/questionnaire/check_status
Content-Type: application/json
X-Token: -B_0_LVu66QlMdb2xp-Vdk_bmHC4j2sS1K9ugfMSLH0

{
}

###

## Update profile
POST http://localhost:8000/questionnaire/answer
Content-Type: application/json
X-Token: YT3EGuBak9IXScZSfGbVzDF7GDayp5zPgaUIeCPmBd0

{
  "suggest": "",
  "incomeInput": 25000,
  "loanInput": 1000000,
  "debtPerMonthInput": 0,
  "totalDebtInput": 0,
  "savingInput": 0,
  "mortgageSecuritiesInput": 0,
  "income": 0,
  "loan": 0,
  "debtPerMonth": 0,
  "totalDebt": 0,
  "saving": 0,
  "mortgageSecurities": 0,
  "ageCode": "1",
  "jobCode": "1",
  "eduCode": "1",
  "timeJobCode": "1",
  "freChangeNameCode": "1",
  "timeOfPhoneNumberCode": "1",
  "timeOfNameInHouseParticularCode": "5",
  "payDebtHistoryCode": "5",
  "statusInHouseParticularCode": "5",
  "haveGuarantorCode": "5",
  "iamGuarantorCode": "5",
  "incomeTrendCode": "5",
  "loanObjectCode": "5",
  "provinceCode": "52"
}

###

## Update profile
POST http://localhost:8000/questionnaire/update
Content-Type: application/json
X-Token: MNOaav8UyaBnwn1bkCTe4wy05IBjodiRd1Zj9lPGk1o

{
  "suggest": "One man",
  "incomeInput": 30000,
  "loanInput": 2000000,
  "debtPerMonthInput": 0,
  "totalDebtInput": 0,
  "savingInput": 0,
  "mortgageSecuritiesInput": 0,
  "income": 0,
  "loan": 0,
  "debtPerMonth": 0,
  "totalDebt": 0,
  "saving": 0,
  "mortgageSecurities": 0,
  "ageCode": "5",
  "jobCode": "10",
  "eduCode": "1",
  "timeJobCode": "1",
  "freChangeNameCode": "1",
  "timeOfPhoneNumberCode": "1",
  "timeOfNameInHouseParticularCode": "5",
  "payDebtHistoryCode": "5",
  "statusInHouseParticularCode": "5",
  "haveGuarantorCode": "5",
  "iamGuarantorCode": "5",
  "incomeTrendCode": "5",
  "loanObjectCode": "5",
  "provinceCode": "52"
}

####

## send questionnaire to verify
POST http://localhost:8000/questionnaire/send
Content-Type: application/json
X-Token: MNOaav8UyaBnwn1bkCTe4wy05IBjodiRd1Zj9lPGk1o

{
  "suggest": "One man",
  "incomeInput": 30000,
  "loanInput": 1000000,
  "debtPerMonthInput": 0,
  "totalDebtInput": 0,
  "savingInput": 0,
  "mortgageSecuritiesInput": 0,
  "income": 0,
  "loan": 0,
  "debtPerMonth": 0,
  "totalDebt": 0,
  "saving": 20000,
  "mortgageSecurities": 1000,
  "ageCode": "5",
  "jobCode": "10",
  "eduCode": "5",
  "timeJobCode": "5",
  "freChangeNameCode": "5",
  "timeOfPhoneNumberCode": "1",
  "timeOfNameInHouseParticularCode": "5",
  "payDebtHistoryCode": "5",
  "statusInHouseParticularCode": "5",
  "haveGuarantorCode": "5",
  "iamGuarantorCode": "5",
  "incomeTrendCode": "5",
  "loanObjectCode": "5",
  "provinceCode": "ถ/"
}

###

## send questionnaire to verify
POST http://localhost:8000/questionnaire/get_questionnaire_data
Content-Type: application/json
X-Token: SS5PzHZE45cMhqlOcu2q8ySUjxuX7T2Kw2zjbqh-iUs

{
}

###
