## Sign In
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
  "username": "superadmin@gmail.com",
  "password": "12345678"
}

###

## Sign In
POST http://35.240.213.218:8000/api/auth/signin
Content-Type: application/json

{
  "username": "superadmin@gmail.com",
  "password": "12345678"
}

###

## Sign out
POST http://localhost:8000/auth/signout
Content-Type: application/json
X-Token: ukbLM9p4-VVWaqfjc8kDIOEty1U_23c6Blut4bJVovg

{
}

###

## worker verify questionniare
POST http://localhost:8000/questionnaire/get_questionnaire_data
Content-Type: application/json
X-Token: Z4Y-HgwwXd2K8-125meWYhHVgRm5Nhzu4FsGE0o80FE

{
}

###


## Get loaner list in status new send questionnaire
POST http://localhost:8000/questionnaire/get_list_new_loaner
Content-Type: application/json
X-Token: ukbLM9p4-VVWaqfjc8kDIOEty1U_23c6Blut4bJVovg

{
}

###

## Get loaner list in status in verify
POST http://localhost:8000/questionnaire/get_list_in_verify
Content-Type: application/json
X-Token: ukbLM9p4-VVWaqfjc8kDIOEty1U_23c6Blut4bJVovg

{
}

###

## Get loaner list in status wait approve
POST http://localhost:8000/questionnaire/get_list_wait_approve
Content-Type: application/json
X-Token: ukbLM9p4-VVWaqfjc8kDIOEty1U_23c6Blut4bJVovg

{
}

###


## Get loaner list in status wait approve
POST http://localhost:8000/questionnaire/count_total_questionnaire
Content-Type: application/json
X-Token: 1qDFrWcAdXMQe-Av63fvEEDtP2cZ6zBugx5Rhm8Tfys

{
}

###
