## Sign In
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
  "username": "korn@gmail.com",
  "password": "12345678"
}

###

## Update profile
POST http://localhost:8000/user/update_profile
Content-Type: application/json
X-Token: jnEeqiiCOqCqtAc0OpmxwgJ-aq77lSqMWCZQf6l7Wk0

{
  "name": "Hoe1",
  "surname": "Gaarden",
  "birthday": "05/07/1990",
  "genderStatus": 1,
  "marriedStatusID": 1,
  "facebook": "tai",
  "ig": "taiIG",
  "line": "taiLine",
  "religion": "-"
}

###

## Update home address
POST http://localhost:8000/user/update_home_address
Content-Type: application/json
X-Token: aZjGC7lDKHnatBPs27FRtHu1-7LhdyCMyxcX7GXyTb4

{
  "address1": "263 หมู่20",
  "subDistrict": "ขามเรียง",
  "district": "กันทรวิชัย",
  "provinceCode": "44",
  "zipCode": "44150"
}

###

## Update office address
POST http://localhost:8000/user/update_office_address
Content-Type: application/json
X-Token: g6cf3mlEWkMEdUci_rdkw7mW_90QuHbWgYA4k82OEqU

{
  "officeName": "subAlgo cop.",
  "provinceCodeOffice": "44",
  "zipCodeOffice": "441"
}

###

## change password
POST http://localhost:8000/user/change_password
Content-Type: application/json
X-Token: XTqc_R-WowISvqZC01JU8BD-ysCpBaD9yA8iqdFOXBQ

{
  "oldPassword": "",
  "newPassword": "",
  "confirmPassword": ""
}

###

## get_profile
POST http://localhost:8000/user/get_profile
Content-Type: application/json
X-Token: 1wRHm9ZQvS9HOlfwh17FqQltdUgSI9bTA7Wr1EhudkM

{
}

###

## get_profile_by_id
POST http://localhost:8000/user/get_profile_by_id
Content-Type: application/json
X-Token: UYVsyg_VOwlcuuDvOr0xniWfoN1NVwmAvBjXjDoX4ig

{
  "userID":
}

###

## get_profile_by_id
POST http://localhost:8000/user/change_forgot_password_question
Content-Type: application/json
X-Token: UYVsyg_VOwlcuuDvOr0xniWfoN1NVwmAvBjXjDoX4ig

{
  "questionID": 0,
  "answer": "ไก่ทอด"
}

###
