## Sign In
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
  "username": "kk@gmail.com",
  "password": "12345678"
}

###

## Update profile
POST http://localhost:8000/user/update_profile
Content-Type: application/json
X-Token: g6cf3mlEWkMEdUci_rdkw7mW_90QuHbWgYA4k82OEqU

{
  "name": "Hoe1",
  "surname": "Gaarden",
  "birthday": "05/07/1990",
  "genderStatus": 1,
  "marriedStatusID": 1,
  "facebook": "tai",
  "ig": "taiIG",
  "line": "taiLine",
  "religion": "-"
}

###

## Update home address
POST http://localhost:8000/user/update_home_address
Content-Type: application/json
X-Token: g6cf3mlEWkMEdUci_rdkw7mW_90QuHbWgYA4k82OEqU

{
  "address1": "263 หมู่20",
  "subDistrict": "ขามเรียง",
  "district": "กันทรวิชัย",
  "provinceCode": "44",
  "zipCode": "44150"
}

###