##redis-cli

## Sign Up
## customer sign up
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "kk@gmail.com",
  "password": "12345678",
  "name": "s1",
  "surname": "ss1",
  "birth": "05/05/1990",
  "phone": "0918651111",
  "marriedStatusID": 1,
  "genderID": 1
}

###

## Sign In
## customer sign up
POST {{baseUrl}}//auth/signin
Content-Type: application/json

{
  "username": "kk@gmail.com",
  "password": "12345678"
}

###

## Sign out
POST {{baseUrl}}//auth/signout
Content-Type: application/json
X-Token: {{user_token}}

{}

###